global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-me'
receivers:
- name: 'email-me'
  email_configs:
  - to: 'emailid'
    from: 'smtp.gmail.com:587'
    smarthost: 'emailid:587'
    auth_username: 'emailid'
    auth_identity: 'emailid'
    auth_password: 'password'
  webhook_configs:
  - url: 'http://<ip/localhost>:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
